import SafariRandomnessPredictor from "../../src/predictors/Safari";
import { describe, it } from "node:test";
import assert from "node:assert";
import queryDb from "../getRandomNumbersFromDatabase";

describe("Safari", () => {
  it(`should predict accurately`, async () => {
    const { sequence, expected } = queryDb("safari", {});
    const p = new SafariRandomnessPredictor(sequence);
    const predictions: number[] = [];
    for (let i = 0; i < expected.length; i++) {
      predictions.push(await p.predictNext());
    }
    assert.deepStrictEqual(expected, predictions);
  });

  it("should predict correctly when numbers were generated using Array.from({ length: 4 }, Math.random)", async () => {
    const { sequence, expected } = queryDb("safari", { arrayFrom: true });
    const p = new SafariRandomnessPredictor(sequence);
    const predictions: number[] = [];
    for (let i = 0; i < expected.length; i++) {
      predictions.push(await p.predictNext());
    }
    assert.deepStrictEqual(expected, predictions);
  });

  it("should predict correctly when numbers were generated by calling Math.random() one at a time", async () => {
    const { sequence, expected } = queryDb("safari", { mathRandomStandalone: true });
    const p = new SafariRandomnessPredictor(sequence);
    const predictions: number[] = [];
    for (let i = 0; i < expected.length; i++) {
      predictions.push(await p.predictNext());
    }
    assert.deepStrictEqual(expected, predictions);
  });
});
