import SafariRandomnessPredictor from "../../src/predictors/Safari";
import { suite, test } from "node:test";
import assert from "node:assert";
import queryDb from "../getRandomNumbersFromDatabase";

suite("Safari", () => {
  const runtime = "safari";

  test(`should predict accurately`, async () => {
    const { sequence, expected } = queryDb({ runtime, tags: {} });
    const p = new SafariRandomnessPredictor(sequence);
    const predictions: number[] = [];
    for (let i = 0; i < expected.length; i++) {
      predictions.push(await p.predictNext());
    }
    assert.deepStrictEqual(expected, predictions);
  });

  test("should predict correctly when numbers were generated using Array.from({ length: 4 }, Math.random)", async () => {
    const { sequence, expected } = queryDb({ runtime, tags: { arrayFrom: true } });
    const p = new SafariRandomnessPredictor(sequence);
    const predictions: number[] = [];
    for (let i = 0; i < expected.length; i++) {
      predictions.push(await p.predictNext());
    }
    assert.deepStrictEqual(expected, predictions);
  });

  test("should predict correctly when numbers were generated by calling Math.random() one at a time", async () => {
    const { sequence, expected } = queryDb({ runtime, tags: { mathRandomStandalone: true } });
    const p = new SafariRandomnessPredictor(sequence);
    const predictions: number[] = [];
    for (let i = 0; i < expected.length; i++) {
      predictions.push(await p.predictNext());
    }
    assert.deepStrictEqual(expected, predictions);
  });
});
