name: publish.yaml
on:
  workflow_run:
    # Depends on these workflows
    workflows: ["tests.yaml"]
    branches: [main]
    types:
      - completed
jobs:
  build:
    # Check if the workflow_run was successful and the commit message starts with "[publish] "
    if: (github.event.workflow_run.conclusion == 'success') && (startsWith(github.event.workflow_run.head_commit.message, '[publish] ')) # intentional space at end of '[publish] '
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # So "Automated Version Bump" can read commit history.
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.2.0
          registry-url: "https://registry.npmjs.org/"
          always-auth: true
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Build files
        run: npm run build
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: "#major"
          minor-wording: "#minor"
          patch-wording: "#patch"
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
