name: test_all_node_versions.yaml
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test-node-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x, 18.x, 20.x, 21.x, 22.x, 23.x, 24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: ./dist
      - name: Run test
        run: |
          npm install
          npm run build
          npm run test:current:nodejs:version
