name: tests_and_publish.yaml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-legacy-node-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Build
        shell: bash
        run: npm run build
      - name: Run tests
        shell: bash
        run: npm run test:nodeVersions16andLess
        env:
          FORCE_COLOR: "1"
  test-supported-node-versions:
    needs: test-legacy-node-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x, 18.x, 19.x, 20.x, 21.x, 22.x, 23.x, 24.x, node] # 'node' means latest stable version
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Echo Node.js version
        run: echo "Node.js version = ${{ matrix.node-version }}"
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Build
        shell: bash
        run: npm run build
      - name: Run tests (v20.x and above)
        if: ${{ matrix.node-version == '20.x' || matrix.node-version == '21.x' || matrix.node-version == '22.x' || matrix.node-version == '23.x' || matrix.node-version == '24.x' || matrix.node-version == 'node' }}
        shell: bash
        run: npm run test:nodeVersions20andGreaterAndBrowsers
        env:
          FORCE_COLOR: 1
      - name: Run tests (v17.x - v19.x) [node:test doesn't exist in these versions]
        if: ${{ matrix.node-version == '17.x' || matrix.node-version == '18.x' || matrix.node-version == '19.x' }}
        shell: bash
        run: npm run test:nodeVersions17to19
        env:
          FORCE_COLOR: 1
  maybe-publish:
    needs: test-supported-node-versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: "https://registry.npmjs.org/"
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Automated Version Bump
        if: startsWith(github.event.head_commit.message, '[publish] ')
        uses: phips28/gh-action-bump-version@v11.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: "#major"
          minor-wording: "#minor"
          patch-wording: "#patch"
      - name: Publish to npm
        if: startsWith(github.event.head_commit.message, '[publish] ')
        shell: bash
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
